baseURL = "https://dennyjohansson.netlify.app/"
languageCode = "en-us"
title = "Denny Johansson blog place"
theme = "cactus"
copyright = "Denny Johansson" # cactus will use title if copyright is not set
disqusShortname = "Denny" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Backlog"
url = "/backlog"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Wth is this? -> I want to come out of my comfort zone and learn how to write and share. I want to document and share what's currently in my mind, if I successfully gets this into a weekly habit it will be a great tool to remember things! I want to nudge myself to create more on my spare time and the need for content might be a great carrot? My main focus will be web development but hopefully other topics will popup (vim, CrossFit, food, Magic the Gathering, keyboards, fermentation)."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
	showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/DennyJohansson"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/denny-johansson"
  [[params.social]]
    name = "email"
    link = "dennybjohansson@gmail.com"  # no need for "mailto:" in the head
